##print( 10 * 3 - 2)
##print( 15 + 10 / 2 - 1)
##print( (3 * 3) - (2 * 2 / 2))
##print( 9 / (5 - 2) + 6)
##x = int(input("Enter a number"))
##y = int(input("Enter a number"))
##z = int(input("Enter a number"))
##print(x*y*z)
##a = 3005
##b = 4.75
##a = float(input("Enter a decimal number"))
##b = float(input("Enter a decimal number"))
##c = float(input("Enter a decimal number"))
##x = int(a)
##y = int(b)
##z = int(c)
##print(x)
##print(y)
##print(z)
print(100*"hi")
