##print(not ( 100 > 10))
##print(4 == -4)
##print(0 <= 0)
##print("i" in "team")
##print("Team" not in "Teamwork")
##print("1" in "123")
##print(3 == 3 and 4 == 4)
##print("A" != "a" and "b" in "bob")
##print((not 3==4)or(not 4<5))
##print(6 <= 7 or 2 + 5 == 7)
##print(max(1,2,3) < 3)
##print(len("C"+"oding")==10)
##print(min(3,2,1) != min(23,78,1))
##print(round(2.3) != 2)
##print(2 + 4 == len("python"))
##print(int("3") == round(3.1))
##a = float(input("enter a decimal number"))
##print(a == 10 or a >= 10)
##a = ("pneumonoultramicroscopicsilicovolcanoconiosis")
##b = (input("Write the longest word you know"))
##print(len(a)<= len(b))
a = int("2")
b = int(input("What is 1+1?"))
print(a == b)
